appId    = "cfb23b33-17f6-475c-b1b0-f3cfaeb5446a"
password = "sGq8Q~y4EoQ4DmEY3NTOlCgM-mD~Wv~OucE92c2k"
#demoPrefix = "terraform-aad-demo"
#demoRegistryPrefix = "arcroweterraformdemo"
demoPrefix = "terraform-azuread-demo"
demoRegistryPrefix = "arcroweterraformaaddemo"
environment = "test"