apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - hashiconf-entra-demo.app

resource "google_compute_managed_ssl_certificate" "managed-cert" {
  name = "managed-cert"

  managed {
    domains = ["hashiconf-entra-demo.app"]
  }
}